services:
  keycloak.auth.api:
    image: ${DOCKER_REGISTRY-}keycloakauthapi
    container_name: Keycloak.Auth.Api
    build:
      context: .
      dockerfile: Services/Keycloak.Auth.Api/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: Keycloak
    command: start-dev
    environment:
      - KC_HEALTH_ENABLED=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./.containers/identity:/opt/keycloak/data
    ports:
      - 18080:8080

  keycloak.auth.proxy:
    image: ${DOCKER_REGISTRY-}keycloakauthproxy
    build:
      context: .
      dockerfile: Services/Keycloak.Auth.Proxy/Dockerfile
    ports:
      - 6000:8080
      - 6001:8081
